### ISSUE TITLE
Use Nuget for windows build dependencies

### ISSUE THREAD

**Issue by zer0n** [Microsoft/caffe#11]
Any update on this, @pavlejosipovic ?

**Comment by pavlejosipovic** [comment]
I've published bvlc_win branch to https://github.com/pavlejosipovic/caffe which uses NuGet for dependencies.
Travis CI is already configured to work on this branch, now I'm working on getting AppVeyor CI (for Windows). Once I'm done I'll RI bvlc_win to Microsoft/caffe.
