### ISSUE TITLE
registry.count(type) == 1 (0 vs. 1) Unknown layer type: MemoryData (known types: )

### ISSUE THREAD

**Issue by Prof-Stephencurry** [Microsoft/caffe#115]
When I add code just like
=========
 namespace caffe  
{  
    extern INSTANTIATE_CLASS(MemoryDataLayer);
     REGISTER_LAYER_CLASS(MemoryData);
}
then ......
Check failed: registry.count(type) == 0 (1 vs. 0) Layer type MemoryData already registered.
I'm crazy......Hope for your answer.~~

**Comment by lopho** [comment]
Same problem here, but with "Input" layer.
`F0811 20:28:35.615144 12572 layer_factory.hpp:81] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type:
Input (known types: )`

**Comment by Prof-Stephencurry** [comment]
@lopho 
I guess I have solved it....
Just  add  extern INSTANTIATE_CLASS(MemoryDataLayer);  only...
you can add
namespace caffe{
.....
 REGISTER_LAYER_CLASS(Input);}
Hope to help you

**Comment by lopho** [comment]
Ah, no, sorry I misread your original bug report. My problem is a different one entirely.
