### ISSUE TITLE
MSB2721 

### ISSUE THREAD

**Issue by Lvhhhh** [microsoft/caffe#139]
win10 gtx1060 vs2013 cuda7.5 cudnnv4

commonsetting is here:
<CudaVersion>7.5</CudaVersion>
        
        <PythonSupport>true</PythonSupport>
        
        <MatlabSupport>false</MatlabSupport>
        <CudaDependencies></CudaDependencies>

        
        <CudaArchitecture>compute_61,sm_61</CudaArchitecture>

        
        <CuDnnPath>D:\cudnn\cudnn-7.0-win-x64-v4.0</CuDnnPath>
        <ScriptsDir>$(SolutionDir)\scripts</ScriptsDir>

when i compile the libcaffe ,it comes out one error

错误	1	error MSB3721: 命令“"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\bin\nvcc.exe" -gencode=arch=compute_61,code=\"sm_61,compute_61\" --use-local-env --cl-version 2013 -ccbin "D:\vs2013\VC\bin\x86_amd64"  -I"E:\caffe\caffe-master\NugetPackages\opencvdefault.3.1.0\build\native\../..//build/native/include/" -I"E:\caffe\caffe-master\NugetPackages\lmdb-v120-clean.0.9.14.0\build\native\..\..\lib\native\include" -I"E:\caffe\caffe-master\NugetPackages\LevelDB-vc120.1.2.0.0\build\native\../..//build/native/include/" -I"E:\caffe\caffe-master\NugetPackages\protobuf-v120.2.6.1\build\native\../..//build/native/include/" -I"E:\caffe\caffe-master\NugetPackages\glog.0.3.3.0\build\native\../..//build/native/include/" -I"E:\caffe\caffe-master\NugetPackages\gflags.2.1.2.1\build\native\../..///build/native/include/" -I"E:\caffe\caffe-master\NugetPackages\boost.1.59.0.0\build\native\..\..\lib\native\include\\" -I"E:\caffe\caffe-master\NugetPackages\hdf5-v120-complete.1.8.15.2\build\native\..\..\lib\native\include" -I"E:\caffe\caffe-master\NugetPackages\OpenBLAS.0.2.14.1\build\native\..\..\lib\native\include" -I"E:\caffe\caffe-master\caffe-master\windows\libcaffe\\..\..\src\\" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\include" -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\include"     --keep-dir E:\caffe\caffe-master\caffe-master\windows\..\Build\Int\libcaffe\x64\Release -maxrregcount=0  --machine 64 --compile -cudart static -Xcudafe "--diag_suppress=exception_spec_override_incompat --diag_suppress=useless_using_declaration --diag_suppress=field_without_dll_interface" -D_SCL_SECURE_NO_WARNINGS -DGFLAGS_DLL_DECL=     -DHAS_OPENCV -DHAS_LMDB -DHAS_HDF5 -DHAS_OPENBLAS -DNDEBUG -D_SCL_SECURE_NO_WARNINGS -DUSE_OPENCV -DUSE_LEVELDB -DUSE_LMDB -DWITH_PYTHON_LAYER -DBOOST_PYTHON_STATIC_LIB -DUSE_CUDNN -D_UNICODE -DUNICODE -Xcompiler "/EHsc /W3 /nologo /Ox /Zi  /MD " -o E:\caffe\caffe-master\caffe-master\windows\..\Build\Int\libcaffe\x64\Release\absval_layer.cu.obj "E:\caffe\caffe-master\caffe-master\src\caffe\layers\absval_layer.cu"”已退出，返回代码为 1。	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\CUDA 7.5.targets	604	9	libcaffe

who can help me

**Comment by Lvhhhh** [comment]
anyone here?!

**Comment by Lipetskikh** [comment]
I have the same problem! Is it any solution?!
