### ISSUE TITLE
Trouble building pycaffe

### ISSUE THREAD

**Issue by by321** [Microsoft/caffe#14]
I'm having trouble building pycaffe, I'm not sure if it's some problem with my local setup. It seems to me there're two issues:

1. The 3rdparty\include\boost\python subdir is missing, and you should copy it from the right boost version. This is the easy part.

2. The real problem for me is that _caffe.cpp includes numpy/arrayobject.h. You can copy the numpy includes into 3rdparty\include, but arrayobject.h causes a few other files to be included, including __multiarray_api.h and _numpyconfig.h. And as far as I can determine, these are not in the numpy source distribution, instead they are generated during the numpy build/installation process. And try as I may, I could not get numpy to build on my machine.

Am I missing something obvious here ? Is there an easier way ?

**Comment by zer0n** [comment]
This issue was already brought up in #6 . It's addressed in @pavlejosipovic 's pull request: https://github.com/Microsoft/caffe/pull/13. Should be available in master soon. If you don't want to wait, consider checking out the branch `bvlc_win`.

**Comment by by321** [comment]
I think the actual fix belongs to wincaffe-3rdparty, which will then be pulled into this project.

Trying to build numpy, I eventually got the "ImportError: cannot import name multiarray" error msg. From web searches I saw this issue is not Windows-specific, people have been having this problem for years on Linux.

**Comment by zer0n** [comment]
You just need to point to the Python lib library with numpy. You shouldn't need to build numpy yourself.

Please follow the instruction here: https://github.com/Microsoft/caffe#python

**Comment by by321** [comment]
OK I'll try, I hope it doesn't conflict with existing python setup.

**Comment by by321** [comment]
OK, got past the compiling step, still have trouble with libs during linking.

**Comment by by321** [comment]
zer0n, do you know if anyone successfully built and run this in python yet ?

Anaconda 2.7 was built using VC for Python 2.7 compiler, which is based on VC 2008
Anaconda 3.5 was built using VC 2015
We're building this using VC 2013

Will it run ?

**Comment by pavlejosipovic** [comment]
It will run with Miniconda 2.7 x64.
Follow Python setup guide https://github.com/Microsoft/caffe#python
After you built Caffe with Python support do the following to run UT.
set PATH=%PATH%<caffe root>\Build\x64\Release
set PythonPath=<caffe root>\Build\x64\Release\pycaffe
python -m unittest discover -s <caffe_root>\python\caffe\test

**Comment by fycus-tree** [comment]
Not working for me. Built from master against full Anaconda 2.7. Obviously the paths are set correct, as it's loading the module. There exists a _caffe.pyd in Release\pycaffe\caffe\

======================================================================
ERROR: test_io (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_io
Traceback (most recent call last):
  File "C:\Anaconda\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Anaconda\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "C:\Users\fycus\caffe\python\caffe\test\test_io.py", line 4, in <module>
    import caffe
  File "C:\Users\fycus\caffe\Build\x64\Release\pycaffe\caffe\__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "C:\Users\fycus\caffe\Build\x64\Release\pycaffe\caffe\pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: DLL load failed: The specified module could not be found.

**Comment by mnidza** [comment]
It definitely looks like Caffe's runtime dependencies cannot be found. Please double-check that <caffe_root>\Build\x64\Release is in your PATH, and that it is separated by a semicolon from previous dirs (if you followed [@pavlejosipovic's comment](https://github.com/Microsoft/caffe/issues/14#issuecomment-182444660) above this may not be the case).

Alternatively, try copying <caffe_root>\Build\x64\Release\*.dll to <caffe_root>\Build\x64\Release\pycaffe\caffe.

**Comment by zer0n** [comment]
Yeah, just copy the DLLs to `Build\x64\Release\pycaffe\caffe`.
