### ISSUE TITLE
caffe.obj : error LNK2001:  cannot explained ..extern symbol: __imp_PyErr_Print,Py_NoneStruct,PyInt_AsLong

### ISSUE THREAD

**Issue by yingwei13mei** [Microsoft/caffe#143]
I suppose compile the whole project's order is libcafffe->caffe->pycaffe....
So I have compiled libcaffe first and got the lib. When I start to compile **caffe**, there comes out:
1>caffe.obj : error LNK2001: 无法解析的外部符号 __imp_PyErr_Print
1>layer_factory.obj : error LNK2001: 无法解析的外部符号 __imp_PyErr_Print
1>libboost_python-vc120-mt-1_59.lib(function_doc_signature.obj) : error LNK2001: 无法解析的外部符号 __imp__Py_NoneStruct
1>libboost_python-vc120-mt-1_59.lib(dict.obj) : error LNK2001: 无法解析的外部符号 __imp__Py_NoneStruct
1>libboost_python-vc120-mt-1_59.lib(module.obj) : error LNK2001: 无法解析的外部符号 __imp__Py_NoneStruct
1>libboost_python-vc120-mt-1_59.lib(function.obj) : error LNK2001: 无法解析的外部符号 __imp__Py_NoneStruct
1>libboost_python-vc120-mt-1_59.lib(tuple.obj) : error LNK2001: 无法解析的外部符号 __imp__Py_NoneStruct
1>libboost_python-vc120-mt-1_59.lib(list.obj) : error LNK2001: 无法解析的外部符号 __imp__Py_NoneStruct
1>libboost_python-vc120-mt-1_59.lib(class.obj) : error LNK2001: 无法解析的外部符号 __imp__Py_NoneStruct
1>libboost_python-vc120-mt-1_59.lib(builtin_converters.obj) : error LNK2001: 无法解析的外部符号 __imp__Py_NoneStruct
1>libboost_python-vc120-mt-1_59.lib(pickle_support.obj) : error LNK2001: 无法解析的外部符号 __imp__Py_NoneStruct
1>libboost_python-vc120-mt-1_59.lib(str.obj) : error LNK2001: 无法解析的外部符号 __imp__Py_NoneStruct
1>libboost_python-vc120-mt-1_59.lib(from_python.obj) : error LNK2001: 无法解析的外部符号 __imp__Py_NoneStruct
...
1>libboost_python-vc120-mt-1_59.lib(list.obj) : error LNK2001: 无法解析的外部符号 __imp_PyInt_AsLong
....

And I have added "C:\Python27\include"  and "C:\Python27\libs" in this proj's configuration. And also modified "CommonSettings.props" file with python option ture and add python path. What else could I do?
Are the Anaconda3 pkgs installed in my "D:\" path  caused this problem?

**Comment by yingwei13mei** [comment]
HAVE DONE

**Comment by snitchjinx** [comment]
Hello, I encountered the same problem. How did you finally solved it?
Also, is it necessary to add python libs and include in the project's configuration? The step is not mentioned in the instructions.
Thank you!
