### ISSUE TITLE
CPU-only builds ?

### ISSUE THREAD

**Issue by by321** [Microsoft/caffe#17]
Are you guys interested in adding CPU-only builds ? I tried this and it actually worked. I see two ways to do this:

1. New, separate project files. The advantage is you don't need to install CUDA dependencies, and project configurations are simpler. The disadvantage is having a new set of project files.

2. Add CPU-only configurations to existing project files.

**Comment by pavlejosipovic** [comment]
In `./windows/CommonSettings.props` set `CpuOnlyBuild` to `true` and it should do the trick.
