### ISSUE TITLE
MatCaffe compilation

### ISSUE THREAD

**Issue by lunzueta** [Microsoft/caffe#19]
I see that in this fork the source of MatCaffe is also available, but I don't see anywhere how it could be compiled for Windows, following the caffe.sln way, configuring the compilation options by editing the CommonSettings.props file. Is there any plan to do it? Or should this be done using an alternative way, like for example, with Cmake?

**Comment by pavlejosipovic** [comment]
We haven't added support for Matlab in Windows fork.
Would you be willing to add it, and make a contribution through pull request?
It would be nice to have support for Octave as well.

**Comment by lunzueta** [comment]
Well, I'm not sure how this could be done in an elegant way, I mean following the way you configure the VS projects like, for example, pycaffe. This fork (https://github.com/happynear/caffe-windows) has a MatCaffe VS2013 project available and I was able to compile and run it correctly in Matlab, but it's been done in a quite different way. I'll have a look and try to contribute, but first I'll need to better understand how to configure the project following your way.
