### ISSUE TITLE
Make the proto generation more roburst

### ISSUE THREAD

**Issue by zer0n** [Microsoft/caffe#2]
The script to generate proto files is in `scripts/GeneratePB.bat`. It checks for existence of output PB files and skips generating new ones if those exist. Need to update the logic so that it checks for changes in the input proto file, not the existence of generated files.

**Comment by zer0n** [comment]
@YuxiaoHu Since you're pretty good at PowerShell, would you please take on this issue?

**Comment by pavlejosipovic** [comment]
In my fork in bvlc_win branch there is proto generation which is robust enough, I'll integrate third back short.

**Comment by zer0n** [comment]
OK, assigning this to you then.

**Comment by zer0n** [comment]
Fixed in PR #13
