### ISSUE TITLE
Log files

### ISSUE THREAD

**Issue by aaronzs** [Microsoft/caffe#21]
I run the cifar10 example and the log information shows in the command line window, but I can't find these log information saved in my caffe root folder. **I'm wondering does this fork of caffe generate `log\*.txt` files while running?**

**Comment by pavlejosipovic** [comment]
Log file will be placed in your temp folder (%temp%).
File name format is in form caffe.exe[machine name].[user].log.INFO...

**Comment by aaronzs** [comment]
@pavlejosipovic Thank you :smiley:
