### ISSUE TITLE
HDF5 link error when compiling a new added project

### ISSUE THREAD

**Issue by 7oud** [Microsoft/caffe#26]
I compiled the solution successfully, however, the compilation failed when trying to add a new proj to the solution. It prompted  "error LNK2001: unresolved external symbol __imp_H5Gclose", as it link hdf5 library failed. I operated as follow

1. Add a new windows console exe to the solution
2. Change configeration from win32 to x64
3. Import CommonSetting.props in Property Manager 
4. Add libcaffe.lib and $(CudaDependencies) linker
5. Use NuGet install other libs
6. Change Warning Level to level1
7. Change Preprocessor Definitions as Project Caffe

And the new project has only one cpp file "main.cpp", which is exactly same to "caffe.cpp". and the new generated "packages.config" is the same too.

One difference I noticed is that in "main.cpp" properties -> C/C++ -> Command Line, it lacks "/I"D:\caffe\NugetPackages\hdf5-v120-complete.1.8.15\build\native\..\..\lib\native\include" " and "/D "HAS_HDF5"" comaring to caffe.cpp in project caffe. it seems adding hdf5 lib linker failed when using NuGet, but in NuGet packages manager, it displayed OK

Could you give some advice about adding a new project for using caffe.lib, a opeation step will be great. thanks a lot!

**Comment by pavlejosipovic** [comment]
I had this issue as well, configuring NuGet packages from VS UI sometimes doesn't do the right thing.
Try fixing Nuget packages manually, you can just c/p from existing projects.

**Comment by 7oud** [comment]
Thanks! could u tell how to fix nuget, which files can be edit manually? 
I want to add a new dll project, I am afraid copy from existing exe project may make some other problems

**Comment by mnidza** [comment]
You should add two lines to the `.vcxproj` file for your project

```
<Import Project="..\..\..\NugetPackages\hdf5-v120-complete.1.8.15\build\native\hdf5-v120.targets" Condition="Exists('..\..\..\NugetPackages\hdf5-v120-complete.1.8.15\build\native\hdf5-v120.targets')" />
```

and 

```
<Error Condition="!Exists('..\..\..\NugetPackages\hdf5-v120-complete.1.8.15\build\native\hdf5-v120.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\..\..\NugetPackages\hdf5-v120-complete.1.8.15\build\native\hdf5-v120.targets'))" />
```
These should be added to the `ImportGroup` and `Target` elements, respectively, probably close to the end of the file. Just look for other similar lines (coming from other NuGet packages that included successfully), or use e.g. `caffe.vcxproj` as an example.

**Comment by 7oud** [comment]
@mnidza It is very helpful, thanks!
