### ISSUE TITLE
error MSB3073

### ISSUE THREAD

**Issue by snailchan** [Microsoft/caffe#28]
Firstly, thank you for your sharing the project. But, when I generated the project after Nuget downloaded the 3rd party, I encountered some errors, for example: cannot open file  "google/protobuf/unknown_field_set.h".
Thus I switched to directory "google/protobuf/", there is only one file. So what can I do for this phenomenon?

**Comment by pavlejosipovic** [comment]
That's strange. 
Can you try to re-add protobuff package to the solution, or just clone the repo in different location (it should trigger NuGet packages to re-download.

**Comment by pavlejosipovic** [comment]
@snailchan did you resolve this issue?

**Comment by snailchan** [comment]
sorry,I have not solved this problem. Actually, I cloned your project, configured it, and debugged it as instruction. However, that didn't work. 
As far as I am concerned, can this problem occurred because the NuGet packages? For I have not found any definitions about the include dir or source dir involved the NuGet packages dir.

**Comment by snailchan** [comment]
After I scanned other issues, I noticed AleksandarTomicMS say that the default location ("C:\Program Files (x86)\Microsoft Visual Studio 12.0")  did matter (https://github.com/Microsoft/caffe/issues/18). Coincidentally，I installed the MSVC in D:\. So, does it really influence?

**Comment by zer0n** [comment]
Can you try `mklink /d "C:\Program Files (x86)\Microsoft Visual Studio 12.0" "D:\Microsoft Visual Studio 12.0"` and verify if it is indeed the case?

**Comment by snailchan** [comment]
Thank you for your help, @pavlejosipovic , @zer0n , after I added the soft link , the original bug disappeared. However, the new bug occurred. 
![error_msb3073](https://cloud.githubusercontent.com/assets/15522308/13570108/3a9999ec-e4a7-11e5-954e-98b331bdcb50.jpg)
I think what causes the error is the '\\scripts' in the first line, but I have searched  nothing useful on google. Can you give some instructions?

**Comment by pavlejosipovic** [comment]
You can try running the cmd script manually to get better error message but my guess is that you haven't configured cuDNN as described in README.md

cuDNN

Download  cuDNN v3  or  cuDNN v4  from nVidia website. Unpack downloaded zip to %CUDA_PATH% (environment variable set by CUDA installer). Alternatively, you can unpack zip to any location and set  CuDnnPath  to point to this location in  .\windows\CommonSettings.props .  Also, you can disable cuDNN by setting  UseCuDNN  to  false  in the property file.

**Comment by snailchan** [comment]
Yes, you are right, @pavlejosipovic . But I had set the $(CuDnnPath) below
![2016-03-08_145338](https://cloud.githubusercontent.com/assets/15522308/13594561/4abb6a82-e540-11e5-9c48-cbad60f7fa0c.jpg)
As I located the cudnn package below
![2016-03-08_145438](https://cloud.githubusercontent.com/assets/15522308/13594586/6db66b4a-e540-11e5-95b5-f442ca5f2171.jpg)
However, this bug still exits. Where did I set wrong?

**Comment by pavlejosipovic** [comment]
If you are using %CUDA_PATH% then you can leave CuDnnPath variable empty.
I'm using cuDNNv4 on my box:
%CUDA_PATH%\bin\cudnn64_4.dll
%CUDA_PATH%\include\cudnn64.h
%CUDA_PATH%\lib\x64\cudnn.lib

**Comment by snailchan** [comment]
thanks, @pavlejosipovic ，your solutions is useful, but, I want to know, why I put the cudnn package in other location have nothing to do with the bug. Where I set wrong?

**Comment by pavlejosipovic** [comment]
You can put cuDNN in any location you want you just need to unzip the cuDNN package you download from NVidia and set CuDnnPath to point to this location
you should have the same folder structure.
<random unpack location>\cuda\bin\cudnn64_4.dll
<random unpack location>\cuda\include\cudnn.h
<random unpack location>\cuda\lib\x64\cudnn.lib

CuDnnPath should point to <random unpack location>
