### ISSUE TITLE
Need help about how to use caffe after build???

### ISSUE THREAD

**Issue by oakkas** [Microsoft/caffe#29]
Hi all.
I build the caffe but do not see release version in build/64 folder. Is that something wrong? Also I could not find how to use it once it is built successfully. I was able to use caffe on ubuntu but the problem was I cannot use gpu version since it is on virtual box.  I'd like to tank in advamce to all.

**Comment by pavlejosipovic** [comment]
Are you sure you have built release version from VS?

**Comment by oakkas** [comment]
I just change the built to resale and I now got the folder for resale. But I still could not get how to use it. Moreover, once I changed the Python and matlab wrapper to true, I got several errors. 
Can someone provide a step by step installation and usage tutorial on this???

Thanks to all

**Comment by pavlejosipovic** [comment]
Look at README.md for basic guidance on building MatLab and Python wrappers.

Caffe is used the same way as in Linux, you can find documentation and examples here: http://caffe.berkeleyvision.org/

**Comment by oakkas** [comment]
I still did not get a good answer but you are closing it??
