### ISSUE TITLE
cudnn.h missing

### ISSUE THREAD

**Issue by oakkas** [Microsoft/caffe#31]
When I set  <UseCuDNN>false</UseCuDNN> to true, I get 
cudnn.h missing error. I checked the Cuda include folder and did not see the header.
Any help will be appreciated. 

Thanks

**Comment by pavlejosipovic** [comment]
Did you follow the steps regarding configuring cuDNN described in README.md?
Which exact variable did you flip from false to true?

**Comment by sasagalic-MSFT** [comment]
@oakkas were you able to solve the problem by following the guild from README.md?

**Comment by mayraDonaji** [comment]
To clarify @pavlejosipovic answer, when the README.md says "Unpack downloaded zip to %CUDA_PATH% " it means that you unzip the files and copy the file of cuda\bin to %CUDA_PATH%\bin, etc. if you copy the folder cuda into %CUDA_PATH% it wont work.
