### ISSUE TITLE
Link error of 'libcaffe.lib'

### ISSUE THREAD

**Issue by KaneZhu** [Microsoft/caffe#33]
> Error	8559	error C2220: warning treated as error - no 'object' file generated (..\..\src\caffe\util\math_functions.cpp)	C:\NugetPackages\boost.1.59.0.0\lib\native\include\boost\format\alt_sstream_impl.hpp	1	1	libcaffe
Error	8561	error LNK1104: cannot open file 'libcaffe.lib'	C:\caffe\windows\caffe.managed\LINK	caffe.managed
Error	8562	error LNK1104: cannot open file 'libcaffe.lib'	C:\caffe\windows\caffe\LINK	caffe
Error	8563	error LNK1104: cannot open file 'libcaffe.lib'	C:\caffe\windows\compute_image_mean\LINK	compute_image_mean
Error	8564	error LNK1104: cannot open file 'libcaffe.lib'	C:\caffe\windows\extract_features\LINK	extract_features
Error	8565	error LNK1104: cannot open file 'libcaffe.lib'	C:\caffe\windows\convert_imageset\LINK	convert_imageset
Error	8582	error LNK1104: cannot open file 'libcaffe.lib'	C:\caffe\windows\matcaffe\LINK	matcaffe
Error	8693	error LNK1104: cannot open file 'libcaffe.lib'	C:\caffe\windows\pycaffe\LINK	pycaffe
Error	8720	error LNK1104: cannot open file 'libcaffe.lib'	C:\caffe\windows\test_all\LINK	test_all

I have no idea what happened. Could you help me?
I am using Cuda 7.5 and VS2013.

**Comment by apanimesh061** [comment]
Hi, I also got same errors along with various other errors related to python builds as well.

I made the following changes to make everything work:

 - Build as Release
 - Install Visual Studio in C:\Program Files (x86)\
   - There are certain modules in openblas that search for paths in C drive. I could not figure out how to change that so I ultimately reinstalled VS in C drive.
- If building python use Python 2.7.11. Causes less warnings.

See if this works?

**Comment by KaneZhu** [comment]
Thank you @apanimesh061 . I found my problem is because the ' warning treated as error '. When I changed the properties of libcaffe to this

>  configurations properties -> C/C++ -> treats warning as error -> No (/WX-)

the project keeps building now. 
I think this properties may be accidentally changed in new updates of the MS Caffe.
