### ISSUE TITLE
Build fail in VS2013, WIN7.

### ISSUE THREAD

**Issue by zwx8981** [Microsoft/caffe#34]
The error information shows as:

![_ maiz4dx6 fd a 6 lvd](https://cloud.githubusercontent.com/assets/14050646/13561141/304f2ecc-e464-11e5-80a0-9cbd392e0685.png)

What's the problem?

**Comment by KaneZhu** [comment]
@zwx8981 I think you got a similar error as me, see my issue #33 .

**Comment by zwx8981** [comment]
@KaneZhu Thank you, but it doesn't work. I seems my Visual Studio 2013 is different somewhat. In my  C:\Program Files (x86)\ folder,  there is no Microsoft Visual Studio 12.0, instead, a Microsoft Visual Studio 11.0 exist. But in C:\Program Files\, there is a Microsoft Visual Studio 12.0. However, to compile this microsoft caffe, I saw E:\NugetPackages\OpenCV.2.4.10\build\native\OpenCV.targets(57,5): error MSB3030: cannot copy file “C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\redist\x64\Microsoft.VC120.CRT\msvcr120.dll . I think that's the problem. So, what's you guys Visual Studio 2013 looks like, is there a Microsoft Visual Studio 12.0 folder in C:\Program Files (x86)\?

**Comment by pavlejosipovic** [comment]
Try building from bvlc_win_to_ms_master_2016_03_11 branch

**Comment by pavlejosipovic** [comment]
bvlc_win_to_ms_master_2016_03_11 is not merged into master, so you can just pull from master.

**Comment by zwx8981** [comment]
@pavlejosipovic Hi, thank you, but I just figured out what the problem is. It seems that the Visual Studio  2013 is required to install in C:\ partition. Is there any to modify some file to fix this problem without re-install the VS2013 to C:\ ?

**Comment by sasagalic-MSFT** [comment]
@zwx8981, as pavlejosipovic said several issues related to VS not being installed at the default location have been fixed with 28081992d8a69e3ec83c9fa34e7f8128f00cb11b. Have you tried pulling the latest master?
If you still experience problems please provide error message.

**Comment by zwx8981** [comment]
@sasagalic-MSFT I‘ve tried it and there is still one error.

error LNK 1104: cannot open file "MSCOREE.lib"

**Comment by Ariex** [comment]
i got similar issue, could give it a try as following: `libcaffe project > Property > C/C++ > General > Treat Warnings as Errors > No (/WX-)`
I think I found it from another issue in BVLC/caffe, but cannot find the link now..

**Comment by sasagalic-MSFT** [comment]
@zwx8981 do you have mscoree.lib in your windows kits installation (path should be something in line with "C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x64")?

**Comment by zwx8981** [comment]
I've successfully built the project now(although I don't know why I can't before.....)
