### ISSUE TITLE
Cannot copy files

### ISSUE THREAD

**Issue by yyyreal** [Microsoft/caffe#35]
Since I'm using the Chinese version of vs2013, I can only describe my issue in the followiing words.

First I meet the issue #34, and I solved it after  I refer to #33, and I recompile "libcaffe.lib"
but errors  occured when the following output was printed on the screen.
![image](https://cloud.githubusercontent.com/assets/13974360/13624866/e85ca592-e5ec-11e5-99a7-83eecedde0a2.png)

It means 
D:\NugetPackages\OpenCV.2.4.10\build\native\OpenCV.targets(57,5): error MSB3030 : cannot copy file " C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\redist\x64\Microsoft.VC120.CRT\msvcr120.dll" , reason : cannot find the file.

I've checked all the instructions and I have no idea where went wrong.

Thanks for you help.

**Comment by zaie** [comment]
你好，不知道在github上面直接用中文是不是有点突兀，刚好我刚解决了这个问题，我直接把vs安装目录里面的vc文件夹，直接全部复制到你贴图中显示的文件夹中了，你可以按照错误里面说的路径打开看，真没有那些文件，所以我就直接复制了，不知道我说清楚没。

**Comment by yyyreal** [comment]
@zaie 谢谢你的建议  我准备试一试

**Comment by AleksandarTomicMS** [comment]
This happens when you have VS installed in location that isn't "C:\Program Files (x86)\Microsoft Visual Studio 12.0". More info can be found in issue #18. This can be solved by adding a link from your VS directory to the expected one:
`mklink /d "C:\Program Files (x86)\Microsoft Visual Studio 12.0" <your VS directory>`

**Comment by yyyreal** [comment]
@AleksandarTomicMS Thanks for your suggestion.  I have installed the VS in "D:\....." indeed. I copy those files to "C:\Program Files (x86)\Microsoft Visual Studio 12.0......."  and I recompile it successfully.
Although I still met some other small issues, I managed to solve them by myself.
