### ISSUE TITLE
roi pooling layer

### ISSUE THREAD

**Issue by zaie** [Microsoft/caffe#37]
There is no roi pooling layer and I want to run faster rcnn. How can I add roi pooling layer into the project?

**Comment by sasagalic-MSFT** [comment]
What is the roi pooling layer? I see no such layer in bvlc/caffe.

**Comment by zaie** [comment]
@sasagalic-MSFT  it's a layer used in faster r_cnn. I can find it there:https://github.com/happynear/caffe-windows/blob/master/src/caffe/layers/roi_pooling_layer.cpp

**Comment by sasagalic-MSFT** [comment]
Microsoft/caffe repo is meant to be mirror of bvlc/caffe (bvlc/caffe/windows for the time being) plus any Microsoft contributions.
Only way to get some functionality here is to make pull request in bvlc/caffe. If accepted, we will pull it.
Other option for you would be to fork Microsoft/caffe on your own and add desired functionality on top of it.

**Comment by pavlejosipovic** [comment]
We will update README.md to better describe purpose of this fork.

**Comment by hoL1day** [comment]
@zaie hello, I want to run faster r-cnn, too. Did you run it successfully? Thanks u~

**Comment by zer0n** [comment]
I already integrated ROI pooling and Smooth L1 Loss layers to support training Faster R-CNN. Please try again.
