### ISSUE TITLE
matlab

### ISSUE THREAD

**Issue by elgo139** [Microsoft/caffe#39]
successful build with VS2013, Win 10, CUDA 7.5 cuDNN and matlab 2105b.

when trying to run from matlab cmd line I get the following error

invalid mex-file "caffe_mex64" the specified module could not be found

tried using dependency checker and many dlls are missing. Is there something incompatible in my setup?

**Comment by mnidza** [comment]
Does it help if you add the `<caffe_root>\Build\x64\Release` into your system path?

**Comment by elgo139** [comment]
Yes!

Thank you!
