### ISSUE TITLE
I can't find this folder <caffe_root>\Build\x64\Release\pycaffe

### ISSUE THREAD

**Issue by SalemAmeen** [Microsoft/caffe#42]
I could not find this folder
<caffe_root>\Build\x64\Release\pycaffe

Instead of that I found this folder <caffe_root>\Build\x64\Release\pycaffe\x64\Debug

please any help

**Comment by sasagalic-MSFT** [comment]
@SalemAmeen what is exact issue you are facing with? Is pycaffe working for you (can you import it to python)?
The output dir structure you describe is rather strange. If you delete build folder and rebuild release do you end up with \Build\x64\Release\pycaffe\x64\Debug path?

**Comment by pavlejosipovic** [comment]
Closing since there was no reply in 5 days, @SalemAmeen  if you are still having issues please re-open this issue.

**Comment by SalemAmeen** [comment]
Hi @pavlejosipovic I could not find the folder when I install the pachage/software and sorry for not reply in last five days as I checked many times and no response.

**Comment by pavlejosipovic** [comment]
I'm not sure what you mean by install the 

> package/software

Also I'm not sure what you mean by 

> I could not find this folder
 \Build\x64\Release\pycaffe

Also you say that you can find 

> \Build\x64\Release\pycaffe\x64\Debug

x64\Debug is just a subfolder of \Build\x64\Release\pycaffe, you should be able to find that as well.

**Comment by SalemAmeen** [comment]
I could not find yet and I am sure the problem I could not understand how to mange to install it, many thanks for your response and help,,,
