### ISSUE TITLE
Issues with caffe.managed

### ISSUE THREAD

**Issue by kg1980** [Microsoft/caffe#43]
I am trying to use caffe.managed.dll in my C# code (just declaring a new CaffeModel).
When the program starts it immediately fails, before getting to the lines where I declare the network.

When I am debugging the code with "Enable native code debugging" I get the following exceptions:
"Microsoft C++ exception: EEFileLoadException * __ptr64 at memory location 0x004da798"

When pressing continue I get:
"Managed Debugging Assistant 'FatalExecutionEngineError' has detected a problem in...
Additional Information: The runtime has encountered a fatal error. The address of the error was at 0xeb982f9b, on thread 0x1df4. The error code is 0x80131506. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack."

I am using visual studio 2013, windows 7. The output is attached
[Output.txt](https://github.com/Microsoft/caffe/files/170973/Output.txt)

**Comment by leizhangcn** [comment]
From the message, it is not clear where the problem is. Can you share your example code or project so that I can take a look?

**Comment by kg1980** [comment]
Thanks for the quick response.
My test project is attached (it's a zip file).
The program is not doing much, but it crashes when I get into the function Run()
I am copying manually all the dll from D:\Caffe\Build\x64\Debug to the program build folder.

[Test.gz](https://github.com/Microsoft/caffe/files/172708/Test.gz)

![image](https://cloud.githubusercontent.com/assets/17811068/13756646/863f7f38-ea29-11e5-8595-646d43ee7b86.png)

**Comment by leizhangcn** [comment]
I checked your sample code. The code itself has no problem. Suppose you have copied all the dlls from the caffe build folder to the program build folder, the test program can run without problems. I didn't meet the problem as you described.

One thing you need to pay attention is that the current managed lib requires the input layer in net prototxt to be `MemoryData`, as shown below:

````
layer {
  name: "data"
  type: "MemoryData"
  top: "data"
  top: "label"
  memory_data_param 
  {
    batch_size: 1
    channels: 3
    height: 256
    width: 256
  }
  transform_param 
  {
    crop_size: 227
    mirror: false
    mean_file: "imagenet_mean.binaryproto"
  }
}

```

Note that to let Caffe find the `mean_file`, you need to change the working directory before calling the constructor, or provide an absolute path for `mean_file`.
 
We have fixed this problem in an internal version, but haven't updated here. You can try this `MemoryData` input first, or wait after we update the managed lib to support the standard deploy prototxt.
