### ISSUE TITLE
win7 vs2013 just say cannot open input file'libcaffe.lib'  and '../util/mkstemp.hpp' no such file or directory

### ISSUE THREAD

**Issue by Kelvinson** [Microsoft/caffe#44]
I just download the master branch build in the mode Release and x64 it says 
error LNK1181: cannot open input file 'libcaffe.lib	'\..Projects\caffe-master\windows\caffe\LINK	caffe
and 
error C1083: Cannot open include file: 'caffe/util/mkstemp.hpp': error C1083: Cannot open include file: 'caffe/util/mkstemp.hpp': No such file or directory (..\..\src\gtest\gtest-all.cpp) 
this error C1083 also exists in many other cpp files
thank you all, guys!!!

![microcaffeerror](https://cloud.githubusercontent.com/assets/16152743/13769014/1805f5cc-eab7-11e5-903d-2ed2b64a1584.JPG)

**Comment by Ariex** [comment]
try do following in VS2013 `libcaffe project > Property > C/C++ > General > Treat Warnings as Errors > No (/WX-)`
not tested in VS2015

**Comment by Kelvinson** [comment]
hi,buddy! I wonder whether you have come across this issue , I set the libcaffe project treat warning not as errors but the problem still exists just like before ,here you can have a careful look at the error messages 
![errror2](https://cloud.githubusercontent.com/assets/16152743/13781058/f98d1d78-eafc-11e5-9d50-3bef17983482.jpg)

I have been installing the caffe on windows for days, how can I make it? thank you very much!

**Comment by Ariex** [comment]
I am sorry that would not help, this is quite new to me
install caffe does not create many issues for me, only there was a time I did not follow the instruction...
sorry again, and good luck~

**Comment by Kelvinson** [comment]
Thanks for your attention, I should have another try.

**Comment by sasagalic-MSFT** [comment]
@Kelvinson are you able to build just libcaffe project?If not could you please provide errors Visual Studio reports.

**Comment by pavlejosipovic** [comment]
@Kelvinson  did you have any luck in building caffe?

**Comment by pavlejosipovic** [comment]
@Kelvinson If you still have issue please reopen the issue.
