### ISSUE TITLE
BinplaceCudaDependencies.cmd fails if the cudnn path has spaces in it 

### ISSUE THREAD

**Issue by alexghitulescu** [Microsoft/caffe#47]
My cudnn path is C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\cudnn. When compiling, BinplaceCudaDependencies.cmd failed saying 'Files\NVIDIA was unexpected at this time.' . I managed to fix this by surrounding %CUDNN_PATH% with quote marks on line 19.

**Comment by j0rre** [comment]
Something similar goes for FixGFlagsNaming.cmd: if the path to the Caffe root directory contains a space, the post build run of this script fails. Running it manually from an arbitrary location by putting both the call and the first argument in quotation marks works.

**Comment by sasagalic-MSFT** [comment]
@alexghitulescu and @j0rre, thank you for reporting the issue. We have verified that issue exists and have a fix for it in a process of merging with master (fix is what you proposed, see ebcd91a64eb669698dbab0719daff50887fc42a5). I will let you know once fix reaches the master.

**Comment by sasagalic-MSFT** [comment]
@alexghitulescu and @j0rre, the fix reached the master ( 5c55969c18226227833117134b59b8a808dc08e3).
