### ISSUE TITLE
Build error in VS2013

### ISSUE THREAD

**Issue by Cogito2012** [Microsoft/caffe#50]
###  When I build the caffe in  VS 2013, error MSB4062 happened like this: 

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\CUDA 7.5.targets(160,9): error MSB4062: 未能从程序集 C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\BuildCustomizations\Nvda.Build.CudaTasks.v7.5.dll 加载任务“Nvda.Build.CudaTasks.SanitizePaths”。未能加载文件或程序集“Microsoft.Build.Utilities.v3.5, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”或它的某一个依赖项。系统找不到指定的文件。 请确认 <UsingTask> 声明正确，该程序集及其所有依赖项都可用，并且该任务包含实现 Microsoft.Build.Framework.ITask 的公共类。

Anyone can solve this problem?

**Comment by mnidza** [comment]
Can you check if you have .NET Framework 3.5 installed?

**Comment by Cogito2012** [comment]
@mnidza I only have .NET Framework 4.5 and 4.6 installed

**Comment by Cogito2012** [comment]
@mnidza I only have .NET Framework 4.5 and 4.6 installed

**Comment by Cogito2012** [comment]
@mnidza I only have .NET Framework 4.5 and 4.6 installed

**Comment by Cogito2012** [comment]
@mnidza I only have .NET Framework 4.5 and 4.6 installed

**Comment by Cogito2012** [comment]
@mnidza I only have .NET Framework 4.5 and 4.6 installed

**Comment by Cogito2012** [comment]
@mnidza I only have .NET Framework 4.5 and 4.6 installed

**Comment by Cogito2012** [comment]
@mnidza I only have .NET Framework 4.5 and 4.6 installed

**Comment by Cogito2012** [comment]
@mnidza I only have .NET Framework 4.5 and 4.6 installed

**Comment by Cogito2012** [comment]
@mnidza I only have .NET Framework 4.5 and 4.6 installed

**Comment by Cogito2012** [comment]
@mnidza I only have .NET Framework 4.5 and 4.6 installed

**Comment by Cogito2012** [comment]
@mnidza I only have .NET Framework 4.5 and 4.6 installed

**Comment by Cogito2012** [comment]
@mnidza I only have .NET Framework 4.5 and 4.6 installed

**Comment by Cogito2012** [comment]
@mnidza I only have .NET Framework 4.5 and 4.6 installed

**Comment by Cogito2012** [comment]
@mnidza I only have .NET Framework 4.5 and 4.6 installed

**Comment by mnidza** [comment]
Try installing .NET 3.5, e.g. through Control Panel ('Turn Windows features on or off') and post back whether it fixed your issue. Some MsBuild tasks for CUDA build seem to depend on .NET 3.5.

**Comment by pavlejosipovic** [comment]
@Cogito2012 If you are still experiencing the issue please reopen the issue.
