### ISSUE TITLE
debug extract features

### ISSUE THREAD

**Issue by BrettLL** [Microsoft/caffe#54]
every time when I debug extract features project, it will happen that 
1>  ProtoCompile.cmd : Create proto include directory
1>  子目录或文件 H:\Project\CAFFE\windows_caffe_dev\caffe-master\windows\..\include\caffe\proto 已经存在。
1>  ProtoCompile.cmd : Compare newly compiled caffe.pb.h with existing one
have you ever meet this problem, and how to solve it? thanks~~

**Comment by sasagalic-MSFT** [comment]
@BrettLL, could you be more specific regarding the issue you are encountering? Are you able to build solution? Are there any errors reported? If so please provide them.

**Comment by pavlejosipovic** [comment]
@BrettLL if you still haven't resolved this issue please re-open it and add more info about issues you are having.
