### ISSUE TITLE
Compiling error when adding a new dll project.

### ISSUE THREAD

**Issue by 7oud** [Microsoft/caffe#55]
I added a new dll project to the solution, most of setting was similar with "caffe.managed". But it compiled error when  including caffe header files, just like "caffe/caffe.hpp". All the errors were in "caffe.pb.h", but all other projects were compiled successfully. So it may be sth wrong with my dll project setting. Could you give some advices?

**Comment by pavlejosipovic** [comment]
maybe you should post the build log for your dll, or maybe push current version somewhere on GitHub?

**Comment by 7oud** [comment]
@pavlejosipovic some errors as follow
![default](https://cloud.githubusercontent.com/assets/7981826/14047215/7c36e22c-f2e1-11e5-86d4-ec2c7d60b5b1.png)
And here is the forked version I pushed.
https://github.com/7oud/caffe-microsoft-fork/tree/master/windows/Classify

**Comment by pavlejosipovic** [comment]
Your problem is that you are including windows.h in precompiled header.
windows.h doesn't play nice with caffe.pb.h. 
In general try to avoid platform dependent code as much as possible.

Solution for is to either disable precompiled header, or just remove windows.h from stdafx.h.
You will have to put windows.h back to dllmain.cpp.

**Comment by 7oud** [comment]
@pavlejosipovic Thanks, it is very helpful!
The dll can be called by exe now, but it still have some problems when running. The code of dll is based on "exmaples\cpp_classification", it seems that layer init was failed, the registry was empty.
https://github.com/7oud/caffe-microsoft-fork/tree/master/windows/Classify

**Comment by pavlejosipovic** [comment]
Looks like you are missing a reference to libcaffe project.
Add something like this https://github.com/7oud/caffe-microsoft-fork/blob/master/windows/pycaffe/pycaffe.vcxproj#L63 to your project file.

**Comment by dereyly** [comment]
Do you build dll version? 
I try to build libcaffe.dll from master version of MS Caffe, and have 2 tipes of errors:
1. Dependencies (3rd party), like boost need to add to project, I do it manually, I think it is mistake, if u know how add all  dependencies libs tell me please
2. Linking cuda errors

**Comment by 7oud** [comment]
@dereyly 
1. libcaffe is a static library (lib) not a dll.
2. Use Nuget to add 3rd party dependencies, if hdf5 can not be added, edit .vcxproj file manually
3. Import CommonSettings.props to link cuda

**Comment by pavlejosipovic** [comment]
@7oud if the original issue is resolved, please close it.
