### ISSUE TITLE
build error on VS2015

### ISSUE THREAD

**Issue by wqvbjhc** [Microsoft/caffe#56]
I use cup only and disable cudnn.
the nuget had download packet in \windows\packages, but the project can't find it. why?

error msg:
This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\..\NugetPackages\OpenCV.2.4.10\build\native\OpenCV.props.	libcaffe	win_caffe\windows\libcaffe\libcaffe.vcxproj	374

**Comment by pavlejosipovic** [comment]
VS2015 is not supported. CUDA doesn't support VS2015.
Additionally most of NuGet packages (used for 3rd party dependencies), don't support VS2015

**Comment by siddasthana** [comment]
I solved it by creating a copy of \caffe-windows\caffe-windows\windows\packages to caffe-windows\NugetPackages.

**Comment by siddasthana** [comment]
You might get additional issues like LINK error for some .lib files. I guess for that you open your nuget manager. Uninstall *VC120 boost lib and install vc140. For VS2015, we need to have vc140 files
