### ISSUE TITLE
run mnist error: caffe check failed

### ISSUE THREAD

**Issue by anxingle** [Microsoft/caffe#57]
8468 im2col.cu 61   caffe check failed;error==cudaSuccess(8 vs.0) invalid device function.....
My GPU is GEFORCE 820m,and installed CUDA7.5。

**Comment by anxingle** [comment]
My CUDA has installed successfully .

**Comment by pavlejosipovic** [comment]
https://github.com/BVLC/caffe/issues/869

**Comment by anxingle** [comment]
Thank you very much!
