### ISSUE TITLE
Use a config file to make builds configurable

### ISSUE THREAD

**Issue by vinjn** [Microsoft/caffe#6]
1. USE_OPENCV is not defined in the project file.
2. pycaffe.vcxproj is not build-able, lacks numpy.

Thx for the project and happy new year!

**Comment by zer0n** [comment]
Thanks. I'm aware of these issues. For (1), `USE_OPENCV` shouldn't be hardcoded. For (2), one needs to specify the Python Directory.

To enable these builds in a clean way, we need to have a config file (similar to [this](https://github.com/MSRDL/caffe/blob/master/Makefile.config.example)) and a script that reads this config file and update the project files.

Or use a `config.props` file and have other project files include this `common.props` file.

**Would you like to work on this task?** I currently don't have bandwidth to work on it soon.

**Comment by vinjn** [comment]
I can take it as a low-prio task.
Will send out PR once completed.

**Comment by zer0n** [comment]
Address in PR #13
