### ISSUE TITLE
Updating the OpenCV dependence

### ISSUE THREAD

**Issue by lunzueta** [Microsoft/caffe#61]
Hi. I've seen that the current version uses OpenCV 2.4.10 as dependence, which is quite outdated, and I had the intention to use a more recent one like OpenCV 3.0 or 3.1. However, in NuGet I've seen that the repo used for this doesn't contain newer versions (https://www.nuget.org/packages/OpenCV/). I've seen that there are other alternative repos (like this: https://www.nuget.org/packages/opencv3/), but even if I've been able to compile Caffe with that, by updating the .vcxproj files and the packages.config files accordingly, then I've seen that I still couldn't run the generated executables (for example test_all.exe) because the OpenCV dll-s were missing. Indeed, they aren't available in that specific NuGet repo, apparently (I'm not an expert user of NuGet). Does this mean that somebody should upload the recent OpenCV versions in a specific way to NuGet, or am I missing something else about how to use NuGet? Did anyone face this issue?

**Comment by pavlejosipovic** [comment]
Looks like the opencv3 uses static linking, so dll's shouldn't be necessary.
Seems like you haven't configured all project properly to use new opencv package.

**Comment by pavlejosipovic** [comment]
My bad, dlls are included through https://www.nuget.org/packages/opencv3.redist/ which is dependency.
I was able to replace existing opecv package just by using UI in VS. It compiles and runs test OK.
If you are having issues configuring it I can share my version somewhere for you to try it out.

**Comment by lunzueta** [comment]
Thanks for the tip @pavlejosipovic. I also realized about that "redist" package, but I wasn't sure how to use it because I see it has the dll-s but not the libs to be linked. So, you mean that you used the VS UI to replace the current OpenCV package by this one? How did you do that exactly?

**Comment by lunzueta** [comment]
@pavlejosipovic Ok, I could finally get this working with OpenCV3. For that, I added both OpenCV3 packages (the "redist" one with the dll files and the one with the lib files) at the same time. I first tried following this tutorial (http://docs.nuget.org/consume/package-manager-dialog) to do this through the VS UI, but I go stuck. This way, I didn't know how to make the system copy the dll files to the corresponding build folder automatically, as other packages do (probably I'm missing something). Then, I just added the "redist" package in a similar way to the other one, also adding the path to the "opencv3.redist.targets" file in the .vcxproj files in the same way as "opencv3.targets".

**Comment by pavlejosipovic** [comment]
To do it through UI you should
* Right click on solution -> Manage NuGet packages for Solution
* Installed packages -> select opencv -> Manage -> uncheck from all projects
* Online -> find package you want to add -> Install -> add to all projects

**Comment by lunzueta** [comment]
@pavlejosipovic Ok, thanks. It's all clear now. Good to know how NuGet works for this. Great tool.
