### ISSUE TITLE
Invalid Mex file 

### ISSUE THREAD

**Issue by Socierducode** [Microsoft/caffe#62]
Hi, everyone! Could you please give me some suggestions to this issues in Matlab, thank you

[scores, maxlabel] = classification_demo(im, 1);
 
Invalid MEX-file 'C:\...\caffemaster\Build\x64\Release\matcaffe\+caffe\private\caffe_.mexw64': not found 

Error in caffe.set_mode_gpu (line 5)
caffe_('set_mode_gpu');

Error in classification_demo (line 66)
  caffe.set_mode_gpu();

**Comment by mnidza** [comment]
Looks like MATLAB cannot fine the `matcaffe` package that you built. Make sure that `<caffe_root>\Build\x64\Release\matcaffe\+caffe\private\caffe_.mexw64` exists, and that your MATLAB and system search paths are set correctly ([instructions](https://github.com/Microsoft/undefined#matlab)). Also, what is your MATLAB working dir when you try to execute `classification_demo`?

**Comment by Socierducode** [comment]
@mnidza Thank you very much for your answers
In fact I tried to execute it under the path <caffe_root>\matlab, but it didn't work because I can't find the caffe_.mexw64 inside, so I had a following plan:
1, copy the demo file under the release path, the invalid file problem came. 
2, copy the caffe_.mexw64 under the <caffe_root>\matlab\+caffe\private, the same problem
<caffe_root>\Build\x64\Release\matcaffe and <caffe_root>\windows\matcaffe  are both added in my matlab path
<caffe_root>\Build\x64\Release\ is added in the system path as well
The caffe_.mexw64 did exist in the release file
Looking forward to your answers 
Thank you very much

**Comment by mnidza** [comment]
@Socierducode All copying should be done automatically by build scripts, you should not have to do any yourself.

I'm guessing that since you tried to run the demo from `<caffe_root>\matlab`, MATLAB incorrectly picked up `<caffe_root>\matlab\+caffe` (which does not contain the MEX) instead of `<caffe_root>\Build\x64\Release\matcaffe\+caffe`. Even if that's the case, it is still strange that your solution 2 did not solve the problem.

Can you try to delete your current `<caffe_root>\Build` folder, rebuild everything, modify search paths _exactly_ according to instructions (without adding any additional paths or copying any files), and try to run the demo from some folder _other_ than `<caffe_root>\matlab`?

**Comment by Socierducode** [comment]
@mnidza Thank you for your answers, I delected all the past files and tried to rebuild your latest scripts, but VS cannot open the libcaffe.lib, should I add some links? I cannot find such a file. Thanks

**Comment by mnidza** [comment]
@Socierducode `libcaffe.lib` is created by building the `libcaffe` project. You should rebuild _the whole solution_, not only one project (e.g. `matcaffe`). That way you ensure that all dependencies for building the MEX, including `libcaffe.lib`, are built.

**Comment by Socierducode** [comment]
@mnidza Thank you for your answers, but I don't understant what you mean, I deleted the "build" folder  I activated the matcaffe in commonsetting.props and tried to rebuild it from the Caffe.sln, but VS cannot open a libcaffe.lib, does the caffe.sln contain whole solution in it? 
lookforward to your answers, thank you
![bug](https://cloud.githubusercontent.com/assets/15711523/14254854/234a800c-fac4-11e5-8384-5285eacdcff6.png)

**Comment by Socierducode** [comment]
@mnidza Thank you very much for your responses, I succeed to build the lastest caffe script, and Matlab folder does contain the caffe_.mexw64 this time, but it doesn't solve the problem, it changes like invalid Mex-file '<caffe_root>\Build\x64\Release\matcaffe\+caffe\private\caffe_.mexw64' : The specified module couldn't be found. So I tried a solution to avoid the system path problem, I copied all the non- folder files in the private folder, it doesn't solve the problem. I search the answers on the Internet, it may have 2 sorts of problems:1, we lose some dll files; 2, the runtime library is imcompactible to the compile time library, but I have no idea how to solve this problem
Looking forward to your answers
Thank you

**Comment by mnidza** [comment]
@Socierducode Again, you should not have to copy any files after the build is done. It is more likely that you're dealing with problem 1, so we can try to debug under that assumption first. For that it would be really useful to go back to state after a clean build, that is

> Can you try to delete your current  <caffe_root>\Build  folder, rebuild everything, modify search paths exactly according to instructions (without adding any additional paths or copying any files), and try to run the demo from some folder other than  <caffe_root>\matlab ?

After that, open MATLAB command window, go to the folder from which you normally execute `classification_demo`, issue the following four commands:

- `version`
- `pwd`
- `path`
- `getenv('PATH')`

and post back their outputs.
