### ISSUE TITLE
different results between ubuntu and windows?

### ISSUE THREAD

**Issue by 7oud** [Microsoft/caffe#65]
A caffe model was trained under the ubuntu. When run the model under windows, the recognition result is differen from the ubuntu's. 
I wonder the reason why different results present by using the same code of Caffe?

**Comment by pavlejosipovic** [comment]
Did you do CPU or GPU trainings, how big are the differences?

**Comment by 7oud** [comment]
The training of the caffemodel is  based on the GPU using the lib of BVLC/caffe under the ubuntu. The same caffemoded is used under the windows with the lib of Microsoft/caffe. The top-1 error of the ubuntu is 9.8%. However, the window's is 16.7%.  One of the diffenent recognition results is as followed:

Ubuntu classification.cpp -gpu
---------- Prediction for 13407253_FC1691_20150708015716.jpg 
0.8397 - BH7141MY
0.0796 - BH7141AY
0.0330 - YQZ7142
0.0231 - CAF7180B48
0.0143 - SVW71611KS

Ubuntu Python -gpu
---------- Prediction for 13407253_FC1691_20150708015716.jpg
	BH7141MY 	0.839395
	BH7141AY 	0.0804996

Ubuntu classification.cpp -cpu
---------- Prediction for 13407253_FC1691_20150708015716.jpg
0.8397 - BH7141MY
0.0796 - BH7141AY
0.0330 - YQZ7142
0.0231 - CAF7180B48
0.0143 - SVW71611KS

Windows classification.cpp -gpu
---------- Prediction for 13407253_FC1691_20150708015716.jpg
0.407078 - CAF7180B48
0.238098 - BH7141MY
0.133654 - YQZ7142
0.0850262 - BH7141AY
0.0409822 - SVW71611KS 

Windows classification.cpp -cpu
---------- Prediction for 13407253_FC1691_20150708015716.jpg
0.407081 - CAF7180B48
0.238097 - BH7141MY
0.133653 - YQZ7142
0.0850261 - BH7141AY 
0.0409822 - SVW71611KS

**Comment by pavlejosipovic** [comment]
Can you make your training public so that we can try it out as well?
Or can you observe this difference on some existing public training?

**Comment by 7oud** [comment]
Thank you for your comments about the question. We have solved the problem.
