### ISSUE TITLE
Unable to build on VS2015

### ISSUE THREAD

**Issue by RGL73** [Microsoft/caffe#7]
Hi 
I tried to build on VS 2015 but I receive 
caffe.vcxproj(35,5): The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\CUDA 7.5.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

any help?
thanks a lot

**Comment by zer0n** [comment]
CUDA 7,5 doesn't integrate with VS 2015 (see [this](http://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/)). That's why I don't recommend using VS 2015 to build caffe yet.

I haven't tried but if you can hack around to make it work on VS 2015, feel free to share your tips.

**Comment by Ariex** [comment]
there are two projects cannot load in VS2015 in my computer, you wall need wo modify the project file to help it find the "CUDA 7.5.props" and "CUDA 7.5.targets" files, then you can load those two projects in VS2015.
Unfortunately, I still cannot make it compile...

**Comment by sammoes** [comment]
You can copy paste those CUDA files to the location in the project files:
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\BuildCustomizations
Which is where CUDA 7.5 seems to put them

Unfortunately there is a problem with the upgrade of NuGet, which VS 2013->2015 seems to miss I think. I get error messages like below. NugetPackages is not a folder in this repository. So I don't know why or where it gets this. If you would replace NugetPackages by \windows\packages\, then you would find the files that appear to be missing. Unfortunately changing NugetPackages to \windows\packages\ in the vcproj files doesn't help the errors. So, I don't know what is going on. The url in the message is a dead link.


Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\..\NugetPackages\boost.1.59.0.0\build\native\boost.targets.	test_all	C:\Users\jd\FaceDetection\caffe\NugetPackages\test_all\test_all.vcxproj	189	

: 

Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\..\..\NugetPackages\OpenBLAS.0.2.14.1\build\native\openblas.targets.	caffe	C:\Users\jd\FaceDetection\caffe\NugetPackages\caffe\caffe.vcxproj	99

**Comment by sammoes** [comment]
Changing paths in NuGet files is not such a good idea... I prefer not to rtfm on NuGet... @Ariex did you get it fixed?

**Comment by pavlejosipovic** [comment]
VS2015 won't be supported until CUDA 8.0 is released.

**Comment by nuernber** [comment]
CUDA 8 RC is now available! https://developer.nvidia.com/cuda-toolkit
