### ISSUE TITLE
output "Transform time,Prefetch batch,Read time"

### ISSUE THREAD

**Issue by superkuanggithub** [Microsoft/caffe#81]
![2](https://cloud.githubusercontent.com/assets/18376522/15096621/2f2dcc14-1534-11e6-865c-ef27ecbf4741.JPG)
the result of program is right(mnist_train).but how can i stop it output Transform time,Prefetch batch and Read time?

**Comment by mnidza** [comment]
Are you running debug build? I think these messages are not output in release build.

**Comment by superkuanggithub** [comment]
@mnidza i comment some codes to solve this problem(//.....).thank you anyway.
