### ISSUE TITLE
the log file

### ISSUE THREAD

**Issue by azhangwei** [Microsoft/caffe#88]
i can't find the information log file(such as INFO2016-05-25T17-30-10.txt), where is it?

**Comment by yang123jx** [comment]
I also can not find the LOG file. Can you tell me if you solve it ?

**Comment by yang123jx** [comment]
I also can not find the LOG file. Can you tell me if you solve it ?

**Comment by azhangwei** [comment]
it is  in the %temp%  location; for example C:\Users\win7\AppData;
